apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: translator-ingress
  namespace: default
  labels:
    team: mjdsft
spec:
  rules:
  - host: mapper.localhost
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: mapper
              port:
                number: 8080
  - host: ingester.localhost
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ingester
              port:
                number: 8080
