apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ingester 
spec:
  selector:
    matchLabels:
      app: ingester 
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: ingester 
        tier: backend
        team: mjdsft
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: ingester-pv-claim
      containers:
      - name: ingester 
        image: mdolbear/ingester:1.0-SNAPSHOT
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: data
          mountPath: /tmp/generatedData
        # the readiness probe details
        readinessProbe:
          httpGet: # make an HTTP request
            port: 8080 # port to use
            path: /ingester/readiness # endpoint to hit
            scheme: HTTP
          initialDelaySeconds: 5 # how long to wait before checking
          periodSeconds: 3 # how long to wait between checks
          successThreshold: 1 # how many successes to hit before accepting
          failureThreshold: 1 # how many failures to accept before failing
          timeoutSeconds: 1 # how long to wait for a response
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1%
      maxUnavailable: 1%
