kind: PersistentVolume
apiVersion: v1
metadata:
  name: ingester-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/tmp/generatedData"
