apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ingester 
spec:
  hosts:
  - ingester 
  http:
  - route:
    - destination:
        host: ingester 
        subset: v1
    fault:
      delay:
        fixedDelay: 3s
        percent: 50
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ingester 
spec:
  host: ingester 
  subsets:
  - name: v1
    labels:
      version: v1
---

