apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ingester 
spec:
  selector:
    matchLabels:
      app: ingester 
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: ingester 
        tier: backend
        team: mjdsft
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: ingester-pv-claim
      containers:
      - name: ingester 
        image: mdolbear/ingester:1.0-SNAPSHOT
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: data
          mountPath: /tmp/generatedData
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1%
      maxUnavailable: 1%
