logging:
  level:
    org.springframework: ERROR
    com.oracle: DEBUG

app:
  applicationName: Mapper
  applicationDescription: ${app.applicationName} is a Spring Boot application

---
management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
      export:
        prometheus:
          enable: true

  endpoints:
    web:
      exposure:
        include: "*"
---

spring:
  profiles:
    active: "test"

---
spring:
    profiles: test
    
---

spring:
  profiles: dev
  data:
     mongodb:
#      uri: mongodb://mongo:27017/db
       host: mongo
       port: 27017
       database: db
server:
    port: 8060

---
spring:
  profiles: prod
  data:
     mongodb:
#      uri: mongodb://mongo:27017/db
       host: mongo
       port: 27017
       database: db

